name: changular2
version: <%= packageJson.version %>
authors:
<%= Object.keys(packageJson.contributors).map(function(name) {
  return '- '+name+' <'+packageJson.contributors[name]+'>';
}).join('\n') %>
description: changular 2 for Dart - a web framework for modern web apps
homepage: <%= packageJson.homepage %>
environment:
  sdk: '>=1.9.0-dev.8.0'
dependencies:
  analyzer: '^0.22.4'
  barback: '^0.15.2+2'
  code_transformers: '^0.2.5'
  dart_style: '^0.1.3'
  html5lib: '^0.12.0'
  stack_trace: '^1.1.1'
dev_dependencies:
  guinness: "^0.1.17"
