name: changular2_benchmarks
version: <%= packageJson.version %>
authors:
<%= Object.keys(packageJson.contributors).map(function(name) {
  return '- '+name+' <'+packageJson.contributors[name]+'>';
}).join('\n') %>
description: changular2 benchmarks
homepage: <%= packageJson.homepage %>
environment:
  sdk: '>=1.9.0-dev.8.0'
dependencies:
  changular2: '^<%= packageJson.version %>'
  browser: '>=0.10.0 <0.11.0'
dependency_overrides:
  changular2:
    path: ../changular2
transformers:
- $dart2js:
    minify: false
    commandLineOptions: ['--dump-info', '--trust-type-annotations', '--trust-primitives']
